# Generated by Django 6.1.1 on 2026-09-29 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'pais'), name='puerto_nombre_pais_unico')],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ruta', models.CharField(choices=[('Directo', 'Directo'), ('Transbordo', 'Transbordo'), ('Directo / Transbordo', 'Directo / Transbordo')], max_length=30)),
                ('puerto_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_destino', to='cotizador.puerto')),
                ('puerto_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='cotizador.puerto')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contenedor', models.CharField(choices=[('20', '20 pies'), ('40', '40 pies')], max_length=2)),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='cotizador.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='TiempoTransito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_minimos', models.PositiveIntegerField()),
                ('dias_maximos', models.PositiveIntegerField()),
                ('ruta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tiempo_transito', to='cotizador.ruta')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(fields=('puerto_origen', 'puerto_destino'), name='ruta_origen_destino_unica'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.UniqueConstraint(fields=('ruta', 'tipo_contenedor'), name='tarifa_ruta_contenedor_unica'),
        ),
    ]
