# Generated by Django 6.1.1 on 2026-09-30 03:42

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='tiempotransito',
            name='dias_maximos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tiempotransito',
            name='dias_minimos',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tipocontenedor',
            name='capacidad_tn',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.CheckConstraint(condition=models.Q(('puerto_origen', models.F('puerto_destino')), _negated=True), name='ruta_origen_destino_distintos'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_minimo__gt', 0)), name='tarifa_minima_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_maximo__gt', 0)), name='tarifa_maxima_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tarifa',
            constraint=models.CheckConstraint(condition=models.Q(('valor_maximo__gte', models.F('valor_minimo'))), name='tarifa_maxima_mayor_igual_minima'),
        ),
        migrations.AddConstraint(
            model_name='tiempotransito',
            constraint=models.CheckConstraint(condition=models.Q(('dias_minimos__gte', 1)), name='transito_minimo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='tiempotransito',
            constraint=models.CheckConstraint(condition=models.Q(('dias_maximos__gte', 1)), name='transito_maximo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='tiempotransito',
            constraint=models.CheckConstraint(condition=models.Q(('dias_maximos__gte', models.F('dias_minimos'))), name='transito_maximo_mayor_igual_minimo'),
        ),
        migrations.AddConstraint(
            model_name='tipocontenedor',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_tn__gt', 0)), name='tipo_contenedor_capacidad_positiva'),
        ),
    ]
