# Generated by Django 6.1.1 on 2026-09-30 04:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_tarifa_valor_maximo_alter_tarifa_valor_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_origen', models.CharField(default='USD', max_length=3)),
                ('moneda_destino', models.CharField(default='CLP', max_length=3)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('fecha_referencia', models.DateField()),
                ('fuente', models.CharField(max_length=100)),
                ('obtenido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_referencia', '-obtenido_en'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor__gt', 0)), name='tipo_cambio_valor_positivo'), models.UniqueConstraint(fields=('moneda_origen', 'moneda_destino', 'fecha_referencia'), name='tipo_cambio_monedas_fecha_unica')],
            },
        ),
    ]
