# Generated by Django 6.1.1 on 2026-09-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puede_gestionar_datos',
            field=models.BooleanField(default=False),
        ),
    ]
